version : '2'
services:
  server:
    container_name: server
    restart: always
    build: .
    ports:
    - '8080:8080'
    # links:
    # - mongo
    volumes: 
    - .:/server
    environment:
    - NODE_ENV=DEVELOPMENT
    - PORT=8080
  # mongo:
  #   container_name: mongo
  #   image: mongo:latest
  #   volumes:
  #   - ./data:/data/db
  #   ports:
  #   - '10000:27017'  